### ISSUE TITLE
Enable File Transfer with video feature active

### ISSUE THREAD

**Issue by robelsharma** [robelsharma/VideoConference#2]
File will be transfer through Relay server. Need to activate it with all other feature.

**Comment by dhakre** [comment]
Even after connecting the whole setup . When I tried to start the video conferencing the 1st client's request to start the video conferencing on 2nd client isn't shown. Can you please help here what should  I do for this?

**Comment by robelsharma** [comment]
First check is the server running and server IP is ping-able from client or not. 

Please create a new issue.
