### ISSUE TITLE
Network Question

### ISSUE THREAD

**Issue by friman** [robelsharma/VideoConference#3]
It only work on LAN? Is not able to work over internet?

**Comment by robelsharma** [comment]
Yes, it only works on LAN. It doesn't have ICE, STUN and TURN so will not work in NATed scenarios.

**Comment by andriani1208** [comment]
after the run project,why video conferences can not perform

**Comment by robelsharma** [comment]
Please create a NEW ticket or issue with all of the information that you are seeing in your java console . Sorry for the delay.
